# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh





[[ -f ~/.shell/common.sh ]] && source ~/.shell/common.sh
[[ -f ~/.shell/zsh.sh ]] && source ~/.shell/zsh.sh
[[ -f ~/.shell/functions.sh ]] && source ~/.shell/functions.sh

# Key bindings
bindkey "^[[1;5C" forward-word   # Ctrl+Right
bindkey "^[[1;5D" backward-word  # Ctrl+Left
bindkey "^[[H"    beginning-of-line  # Home
bindkey "^[[F"    end-of-line        # End
bindkey "^[[3~"   delete-char        # Delete

# zshrc history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000

setopt appendhistory
setopt incappendhistory
setopt sharehistory
setopt hist_ignore_dups
setopt hist_reduce_blanks

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=('/home/grasvis/.juliaup/bin' $path)
export PATH
# Tab completion for juliaup and julia channel selection
[ -f "/home/grasvis/.julia/juliaup/completions/zsh.zsh" ] && source "/home/grasvis/.julia/juliaup/completions/zsh.zsh"

# <<< juliaup initialize <<<

. "$HOME/ubuntu/shell/claude.sh"

bindkey -v
